package sales

type RegisterSalesModel struct {
	CardID      string `json:"card_id"`
	Fname       string `json:"f_name"`
	Lname       string `json:"l_name"`
	URLCardID   string `json:"url_card_id"`
	URLBookBank string `json:"url_book_bank"`
	URLFirstBuy string `json:"url_slip_first_buy"`
	File3       string `json:"file_url_3"`
	BookBankID  string `json:"book_bank_id"`
	BankCode    string `json:"bank_code"`
	BankName    string `json:"bank_name"`
}

type UpdateSaleModel struct {
	CardID      string `json:"card_id"`
	Fname       string `json:"f_name"`
	Lname       string `json:"l_name"`
	URLCardID   string `json:"url_card_id"`
	URLBookBank string `json:"url_book_bank"`
	URLFirstBuy string `json:"url_slip_first_buy"`
	File3       string `json:"file_url_3"`
	BookBankID  string `json:"book_bank_id"`
	BankCode    string `json:"bank_code"`
	BankName    string `json:"bank_name"`
	Confirm     int64  `json:"confirm"`
}

type Node struct {
	InvitePerson int64 `json:"invite_person"`
}
type UpdateSaleModelAdmin struct {
	SaleCode    string `json:"sales_code"`
	CardID      string `json:"card_id"`
	Fname       string `json:"f_name"`
	Lname       string `json:"l_name"`
	URLCardID   string `json:"url_card_id"`
	URLBookBank string `json:"url_book_bank"`
	URLFirstBuy string `json:"url_slip_first_buy"`
	File3       string `json:"file_url_3"`
	BookBankID  string `json:"book_bank_id"`
	BankCode    string `json:"bank_code"`
	BankName    string `json:"bank_name"`
	Confirm     int64  `json:"confirm"`
	Cancel      int64  `json:"cancel"`
}

type ModelStructureSales struct {
	CompanyID    int64                 `json:"company_id" db:"company_id"`
	RoleID       int64                 `json:"role_id" db:"role_id"`
	RoleName     string                `json:"role_name" db:"role_name"`
	ProfixName   string                `json:"profix_name" db:"profix_name"`
	Fname        string                `json:"fname" db:"user_fname"`
	Lname        string                `json:"lname" db:"user_lname"`
	ActiveStatus int64                 `json:"active_status" db:"active_status"`
	Telephone    string                `json:"telephone" db:"telephone"`
	Email        string                `json:"email" db:"email"`
	RefCode      string                `json:"ref_code" db:"ref_code"`
	InviteCode   string                `json:"invite_code" db:"invite_code"`
	InvitePerson int64                 `json:"invite_person"`
	Invite       []ModelStructureSales `json:"invite,omitempty"`
}

// Generated by https://quicktype.io

type ModelSale struct {
	ID           int64                 `json:"id" db:"id"`
	UserID       string                `json:"user_id" db:"user_id"`
	SalesCode    string                `json:"sales_code" db:"sales_code"`
	FirstName    string                `json:"first_name" db:"first_name"`
	InvitePerson int64                 `json:"invite_person"`
	LastName     string                `json:"last_name" db:"last_name"`
	RoleID       int64                 `json:"role_id" db:"role_id"`
	RoleName     string                `json:"role_name" db:"role_name"`
	CardID       string                `json:"card_id" db:"card_id"`
	BookBankID   string                `json:"book_bank_id" db:"book_bank_id"`
	Age          int64                 `json:"age" db:"age"`
	URLCardID    string                `json:"url_card_id" db:"url_card_id"`
	URLBookBank  string                `json:"url_book_bank" db:"url_book_bank"`
	URLFirstBuy  string                `json:"url_slip_first_buy" db:"url_slip_first_buy"`
	FileURL3     string                `json:"file_url_3" db:"file_url_3"`
	Telephone    string                `json:"telephone" db:"telephone"`
	InviteCode   string                `json:"invite_code" db:"invite_code"`
	Confirm      int64                 `json:"confirm" db:"confirm"`
	BankCode     string                `json:"bank_code" db:"bank_code"`
	BankName     string                `json:"bank_name" db:"bank_name"`
	CreateDate   string                `json:"create_date" db:"create_date"`
	Invite       []ModelStructureSales `json:"invite,omitempty"`
}

// Generated by https://quicktype.io

type ModeOrder struct {
	ID          string  `json:"id"`
	UserID      string  `json:"user_id"`
	DocNo       string  `json:"doc_no"`
	RefDocDate  string  `json:"ref_doc_date"`
	FName       string  `json:"f_name"`
	LName       string  `json:"l_name"`
	TotalAmount float64 `json:"total_amount"`
}

// Generated by https://quicktype.io

type ModelCommision struct {
	ID               int64               `json:"id" db:"id"`
	UserID           string              `json:"user_id" db:"user_id"`
	SalesCode        string              `json:"sales_code" db:"sales_code"`
	FName            string              `json:"f_name" db:"f_name"`
	LName            string              `json:"l_name" db:"l_name"`
	Telephone        string              `json:"telephone" db:"telephone"`
	DocNo            string              `json:"doc_no" db:"doc_no"`
	DocDate          string              `json:"doc_date" db:"doc_date"`
	TotalAmount      float64             `json:"total_amount" db:"total_amount"`
	ALLSaleCommision float64             `json:"all_sale_commision" db:"all_sale_commision"`
	BankInfo         BankInfoModel       `json:"bank_info"`
	Status           int64               `json:"status" db:"status"`
	MyDescription    string              `json:"my_description" db:"my_description"`
	SlipApprove      string              `json:"slip_approve" db:"slip_approve"`
	Confirm          int64               `json:"confirm" db:"confirm"`
	ConfirmTime      string              `json:"confirm_time" db:"confirm_time"`
	Sub              []ModelCommisionSub `json:"sub"`
}
type BankInfoModel struct {
	CardID      string `json:"card_id" db:"card_id"`
	URLCardID   string `json:"url_card_id" db:"url_card_id"`
	BookBankID  string `json:"book_bank_id" db:"book_bank_id"`
	URLBookBank string `json:"url_book_bank" db:"url_book_bank"`
	BankCode    string `json:"bank_code" db:"bank_code"`
	BankName    string `json:"bank_name" db:"bank_name"`
}

// Generated by https://quicktype.io

type ModelCommisionSub struct {
	ID          int64   `json:"id"`
	OrderDoc    string  `json:"order_doc"`
	OrderDate   string  `json:"order_date"`
	UserID      string  `json:"user_id"`
	FName       string  `json:"f_name"`
	LName       string  `json:"l_name"`
	TotalAmount float64 `json:"total_amount"`
}

type ModelSaleV2 struct {
	ID           int64   `json:"id" db:"id"`
	UserID       string  `json:"user_id" db:"user_id"`
	SalesCode    string  `json:"sales_code" db:"sales_code"`
	FirstName    string  `json:"first_name" db:"first_name"`
	InvitePerson int64   `json:"invite_person"`
	LastName     string  `json:"last_name" db:"last_name"`
	RoleID       int64   `json:"role_id" db:"role_id"`
	RoleName     string  `json:"role_name" db:"role_name"`
	CardID       string  `json:"card_id" db:"card_id"`
	BookBankID   string  `json:"book_bank_id" db:"book_bank_id"`
	Age          int64   `json:"age" db:"age"`
	Sale         float64 `json:"sale"`
	InviteSale   float64 `json:"invite_sale"`
	Commission   float64 `json:"commission"`
	AllSale      float64 `json:"all_sale"`
	URLCardID    string  `json:"url_card_id" db:"url_card_id"`
	URLBookBank  string  `json:"url_book_bank" db:"url_book_bank"`
	URLFirstBuy  string  `json:"url_slip_first_buy" db:"url_slip_first_buy"`
	FileURL3     string  `json:"file_url_3" db:"file_url_3"`
	InviteCode   string  `json:"invite_code" db:"invite_code"`
	Incentive    float64 `json:"incentive"`
	Confirm      int64   `json:"confirm" db:"confirm"`
	CreateDate   string  `json:"create_date"`

	Level  []ModelallSalelevel     `json:"all_level"`
	Invite []ModelStructureSalesV2 `json:"invite,omitempty"`
}

type ModelStructureSalesV2 struct {
	CompanyID    int64   `json:"company_id" db:"company_id"`
	RoleID       int64   `json:"role_id" db:"role_id"`
	UserID       string  `json:"user_id" db:"user_id"`
	RoleName     string  `json:"role_name" db:"role_name"`
	ProfixName   string  `json:"profix_name" db:"profix_name"`
	Fname        string  `json:"fname" db:"user_fname"`
	Lname        string  `json:"lname" db:"user_lname"`
	ActiveStatus int64   `json:"active_status" db:"active_status"`
	Telephone    string  `json:"telephone" db:"telephone"`
	Email        string  `json:"email" db:"email"`
	RefCode      string  `json:"ref_code" db:"ref_code"`
	InviteCode   string  `json:"invite_code" db:"invite_code"`
	InvitePerson int64   `json:"invite_person"`
	Sale         float64 `json:"sale"`
	InviteSale   float64 `json:"invite_sale"`
	Commission   float64 `json:"commission"`

	Invite []ModelStructureSalesV2 `json:"invite,omitempty"`
}

type ModelLinkTeamsale struct {
	UserID      string  `json:"user_id"`
	RoleID      int64   `json:"role_id"`
	AllTeamSale float64 `json:"all_team_sale"`
}

// Generated by https://quicktype.io

type CommisionModel struct {
	ID               int64   `json:"id" db:"id"`
	NameRank         string  `json:"name_rank" db:"name_rank"`
	CommisionPercent int64   `json:"commision_percent" db:"commision_percent"`
	TaxRate          float64 `json:"tax_rate" db:"tax_rate"`
	TaxStatus        int64   `json:"tax_status" db:"tax_status"`
}

type ModelInviteLevel struct {
	Level        int64 `json:"level"`
	ALLSaleLevel float64
	InviteList   []ModelSale `json:"invite,omitempty"`
}

type ModelLevel struct {
	Level            int64       `json:"level"`
	AllSaleLevel     float64     `json:"all_sale_level"`
	AllSaleNextLevel float64     `json:"all_sale_next_level"`
	SumSale          float64     `json:"sum_sale_level"`
	NextLevel        *ModelLevel `json:"next_level"`
}

type ModelallSalelevel struct {
	Level   int64   `json:"level"`
	Allsale float64 `json:"all_sale"`
}
type ModelallsaleInvite struct {
	AllsaleInvite float64             `json:"all_sale_invite"`
	AllLevel      int64               `json:"all_level"`
	Level         []ModelallSalelevel `json:"level"`
}
