package report

// Generated by https://quicktype.io

type ModelReportSale struct {
	DocNo            string  `json:"doc_no" db:"doc_no"`
	UserID           string  `json:"user_id" db:"user_id"`
	UserName         string  `json:"user_name" db:"user_name"`
	CreateTime       string  `json:"create_time" db:"create_time"`
	Amount           float64 `json:"amount" db:"amount"`
	CommisionAmount  float64 `json:"commision_amount"`
	CommisionPercent float64 `json:"comision_percent"`
	SaleType         string  `json:"sale_type" db:"sale_type"`
}
