package admin

type UserModelPhone struct {
	Code     string `json:"telephone" db:"telephone"`
	Password string `json:"pwd" db:"pwd"`
}

type UserModelEmail struct {
	Code     string `json:"email" db:"email"`
	Password string `json:"pwd" db:"pwd"`
}

type UserModel struct {
	Code     string `json:"code"`
	Password string `json:"password"`
}
type AdminProfileModel struct {
	AdminID      string          `json:"admin_id" db:"admin_code"`
	CompanyID    int64           `json:"company_id" db:"company_id"`
	RoleID       int64           `json:"role_id" db:"role_id"`
	RoleName     string          `json:"role_name" db:"role_name"`
	ProfixName   string          `json:"prefix_name" db:"profix_name"`
	Fname        string          `json:"fname" db:"user_fname"`
	Lname        string          `json:"lname" db:"user_lname"`
	ActiveStatus int64           `json:"active_status" db:"active_status"`
	Phone        string          `json:"phone" db:"phone"`
	Email        string          `json:"email" db:"email"`
	Menu         []HeadMenuModel `json:"menu"`
}
type HeadMenuModel struct {
	HeadMenuID         int64          `json:"head_menu_id" db:"head_menu_id"`
	HeadManuName       string         `json:"head_manu_name" db:"head_manu_name"`
	HeadMenuIcon       string         `json:"head_menu_icon" db:"head_menu_icon"`
	HeadMenuLineNumber int64          `json:"head_menu_line_number" db:"head_menu_line_number"`
	Notify             int64          `json:"noti"`
	Sub                []SubMenuModel `json:"sub"`
}

// Generated by https://quicktype.io
type SubMenuModel struct {
	MenuID         int64  `json:"menu_id"`
	HeadMenuID     int64  `json:"head_menu_id"`
	MenuName       string `json:"menu_name"`
	MenuLink       string `json:"menu_link"`
	MenuShow       int64  `json:"menu_show"`
	MenuStatus     int64  `json:"menu_status"`
	MenuLineNumber int64  `json:"menu_line_number"`
	Notify         int64  `json:"noti"`
} // Generated by https://quicktype.io

type ModelRole struct {
	RoleID       string `json:"role_id"`
	RoleName     string `json:"role_name"`
	ActiveStatus int64  `json:"active_status"`
	Type         int64  `json:"type"`
}

type UpdateUserProfileModel struct {
	AdminID      string `json:"admin_id" db:"admin_code"`
	CompanyID    int64  `json:"company_id" db:"company_id"`
	RoleID       int64  `json:"role_id" db:"role_id"`
	RoleName     string `json:"role_name" db:"role_name"`
	ProfixName   string `json:"prefix_name" db:"profix_name"`
	Fname        string `json:"fname" db:"user_fname"`
	Lname        string `json:"lname" db:"user_lname"`
	ActiveStatus int64  `json:"active_status" db:"active_status"`
	Phone        string `json:"phone" db:"phone"`
	Email        string `json:"email" db:"email"`
	Password     string `json:"password"`
}

type AddadminBackEndModel struct {
	CompanyID  int64  `json:"company_id" db:"company_id"`
	RoleID     int64  `json:"role_id" db:"role_id"`
	ProfixName string `json:"prefix_name" db:"profix_name"`
	Fname      string `json:"fname" db:"user_fname"`
	Lname      string `json:"lname" db:"user_lname"`
	Phone      string `json:"phone" db:"phone"`
	Email      string `json:"email" db:"email"`
	Password   string `json:"password" db:"pwd"`
}
