package member

import "gitlab.com/satit13/perfect_api/sales"

type ProfileModel struct {
	UserID  string                `json:"user_id"`
	Profile ProfileMemberModel    `json:"member_profile"`
	Address []AddressProfileModel `json:"member_address"`
}

type ProfileMemberModel struct {
	Email     string `json:"mb_email"`
	Phone     string `json:"mb_phone"`
	ShopName  string `json:"mb_name"`
	Gender    int64  `json:"mb_gender"`
	BrithDate string `json:"mb_birth_date"`
}

type AddressProfileModel struct {
	AddressID   int64  `json:"addr_id,omitempty" db:"addr_id,omitempty"`
	Name        string `json:"addr_name" db:"addr_name"`
	Phone       string `json:"addr_phone" db:"addr_phone"`
	Email       string `json:"addr_email" db:"addr_email"`
	Address     string `json:"addr_state" db:"addr_state"`
	SubArea     string `json:"addr_subarea" db:"addr_subarea"`
	District    string `json:"addr_district" db:"addr_district"`
	Province    string `json:"addr_province" db:"addr_province"`
	PostalCode  int64  `json:"addr_postal_code" db:"addr_postal_code"`
	MainAddress int    `json:"main_address" db:"main_address"`
}

type AddAddressModel struct {
	UserID  string              `json:"user_id"`
	Address AddressProfileModel `json:"member_address"`
}
type UserProfileModelBackEnd struct {
	CompanyID int64  `json:"company_id" db:"company_id"`
	UserID    string `json:"user_id" db:"user_id"`
	RoleID    int64  `json:"role_id" db:"role_id"`
	RoleName  string `json:"role_name" db:"role_name"`
	Dealer    int64  `json:"dealer"`
	// UserID       string                `json:"user_id" db:"user_id"`
	ProfixName        string `json:"profix_name" db:"profix_name"`
	SalesStatus       int64  `json:"sales_status"`
	Fname             string `json:"fname" db:"user_fname"`
	Lname             string `json:"lname" db:"user_lname"`
	FirstBuy          int64  `json:"first_buy"`
	ActiveStatus      int64  `json:"active_status" db:"active_status"`
	Telephone         string `json:"telephone" db:"telephone"`
	Email             string `json:"email" db:"email"`
	DicountPerson     string `json:"discount_person"`
	DiscountExpirDate string `json:"discount_expridate"`
	RefCode           string `json:"ref_code" db:"ref_code"`
	InviteCode        string `json:"invite_code" db:"invite_code"`
	InvitePerson      int64  `json:"invite_person"`
	CreateDate        string `json:"create_date" db:"create_time"`
}
type UpdateUserProfileModelByAdmin struct {
	UserID    string `json:"user_id" db:"user_id"`
	CompanyID int64  `json:"company_id" db:"company_id"`
	RoleID    int64  `json:"role_id" db:"role_id"`
	// UserID       string `json:"user_id,omitempty" db:"user_id"`
	ProfixName   string `json:"profix_name" db:"profix_name"`
	Fname        string `json:"fname" db:"user_fname"`
	Lname        string `json:"lname" db:"user_lname"`
	ActiveStatus int64  `json:"active_status" db:"active_status"`
	Telephone    string `json:"telephone" db:"telephone"`
	//RefCode      string `json:"ref_code" db:"ref_code"`
	Email string `json:"email" db:"email"`
}

type UserProfileModel struct {
	CompanyID int64  `json:"company_id" db:"company_id"`
	RoleID    int64  `json:"role_id" db:"role_id"`
	RoleName  string `json:"role_name" db:"role_name"`
	Dealer    int64  `json:"dealer"`
	// UserID       string                `json:"user_id" db:"user_id"`
	ProfixName        string                      `json:"profix_name" db:"profix_name"`
	SalesStatus       int64                       `json:"sales_status"`
	Fname             string                      `json:"fname" db:"user_fname"`
	Lname             string                      `json:"lname" db:"user_lname"`
	FirstBuy          int64                       `json:"first_buy"`
	ActiveStatus      int64                       `json:"active_status" db:"active_status"`
	Telephone         string                      `json:"telephone" db:"telephone"`
	Email             string                      `json:"email" db:"email"`
	DicountPerson     string                      `json:"discount_person"`
	DiscountExpirDate string                      `json:"discount_expridate"`
	RefCode           string                      `json:"ref_code" db:"ref_code"`
	InviteCode        string                      `json:"invite_code" db:"invite_code"`
	InvitePerson      int64                       `json:"invite_person"`
	CreateDate        string                      `json:"create_date" db:"create_time"`
	Invite            []sales.ModelStructureSales `json:"invite,omitempty"`

	// AccessToken  string                `json:"access_token" db:"access_token"`
	Address []AddressProfileModel `json:"member_address"`
	Menu    []HeadMenuModel       `json:"menu"`
	Coupon  []ModelCoupon         `json:"list_coupon"`
}

// Generated by https://quicktype.io

type ModelCoupon struct {
	ID           int64   `json:"id" db:"id"`
	DocDate      string  `json:"doc_date" db:"doc_date"`
	CouponNo     string  `json:"coupon_no" db:"coupon_no"`
	CouponType   int64   `json:"coupon_type" db:"coupon_type"`
	UserID       string  `json:"user_id" db:"user_id"`
	Name         string  `json:"name" db:"name"`
	Value        float64 `json:"value" db:"value"`
	Remain       float64 `json:"remain" db:"remain"`
	ExpireStatus int64   `json:"expire_status" db:"expire_status"`
	BeginDate    string  `json:"begin_date" db:"begin_date"`
	ExpireDate   string  `json:"expire_date" db:"expire_date"`
}

type UpdateUserProfileModel struct {
	CompanyID int64 `json:"company_id" db:"company_id"`
	RoleID    int64 `json:"role_id" db:"role_id"`
	// UserID       string `json:"user_id,omitempty" db:"user_id"`
	ProfixName   string `json:"profix_name" db:"profix_name"`
	Fname        string `json:"fname" db:"user_fname"`
	Lname        string `json:"lname" db:"user_lname"`
	ActiveStatus int64  `json:"active_status" db:"active_status"`
	Telephone    string `json:"telephone" db:"telephone"`
	//RefCode      string `json:"ref_code" db:"ref_code"`
	Email string `json:"email" db:"email"`
}

// Generated by https://quicktype.io

type HeadMenuModel struct {
	HeadMenuID         int64          `json:"head_menu_id" db:"head_menu_id"`
	HeadManuName       string         `json:"head_manu_name" db:"head_manu_name"`
	HeadMenuIcon       string         `json:"head_menu_icon" db:"head_menu_icon"`
	HeadMenuLineNumber int64          `json:"head_menu_line_number" db:"head_menu_line_number"`
	Sub                []SubMenuModel `json:"sub"`
}

// Generated by https://quicktype.io
type SubMenuModel struct {
	MenuID         int64  `json:"menu_id"`
	HeadMenuID     int64  `json:"head_menu_id"`
	MenuName       string `json:"menu_name"`
	MenuLink       string `json:"menu_link"`
	MenuShow       int64  `json:"menu_show"`
	MenuStatus     int64  `json:"menu_status"`
	MenuLineNumber int64  `json:"menu_line_number"`
}

type ListMember struct {
	Users []UserProfileModel
}
