package menu

type RegisterSalesModel struct {
	CardID string `json:"card_id"`
	Fname  string `json:"f_name"`
	Lname  string `json:"l_name"`
	File1  string `json:"file_url_1"`
	File2  string `json:"file_url_2"`
}

// Generated by https://quicktype.io

type ModelSale struct {
	ID         int64  `json:"id"`
	UserID     string `json:"user_id"`
	SalesCode  string `json:"sales_code"`
	FirstName  string `json:"first_name"`
	LastName   string `json:"last_name"`
	CardID     string `json:"card_id"`
	IfnullAge0 int64  `json:"ifnull(age,0)"`
	FileURL1   string `json:"file_url_1"`
	FileURL2   string `json:"file_url_2"`
}
